FROM eclipse-temurin:21-jdk-alpine
LABEL maintainer="Ogo Okafor"
COPY target/inventory-service-0.0.1-SNAPSHOT.jar inventory-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "inventory-service-0.0.1-SNAPSHOT.jar"]